### PR TITLE
Kevin

### PR DESCRIPTION
**Pull request by kevinlmadison**
@pbateman828 included l_init.cpp in main instead of l_init.h and that made it build. I haven't investigated why exactly this is necessary but l_init.cpp is only functions and no classes so it might just not need a header file I think.

### CODE REVIEW

**Comment by pbateman828** [comment]
You can merge. I will try it with a header file only and see if that works.

**Comment by pbateman828** [comment]
I don't understand why you have to include the .cpp file

**Comment by kevinlmadison** [comment]
yo

**Comment by dmadisetti** [comment]
Does Bernard live?

**Comment by kevinlmadison** [comment]
Bernard might see some resurgence ;D

**Pull request merged**
